### ISSUE TITLE
Tests and coverage

### ISSUE THREAD

**Issue by ChrisChV** [PauloniaAQP/paulonia_cache_image#14]
For deploy the first stable version, tests and at least 75% of coverage is needed in the package

**Comment by pcelis19** [comment]
Hey, could you expand on,

> 'Null safety: This package supports Null safety but due to an error the null-safety badge is not placed', 

Is this (1) an _**error**_ on pub.dev's end, or is (2) the package itself having the _**error**_? If it is 2, could you expand on that, please.

**Comment by ChrisChV** [comment]
Hi @pcelis19, Sorry for not placing a more detailed explanation in the README

We use the [hive package](https://pub.dev/packages/hive_flutter/versions), in their package they have the [same badge problem](https://pub.dev/packages/hive_flutter/score). It could be said that we inherited that problem, for now, it is not in our hands (unless we change the package, but for a badge, it is not worth it).

It is a problem with `dart:indexed_db` and the error is: `dart:indexed_db where dart:indexed_db is inaccessible`. This is the issue on hive's github: https://github.com/hivedb/hive/issues/688

Apparently it is only a problem with the pub points and the null-safety badge since if you use the `dart pub outdated --mode=null-safety` command, both `hive` and `paulonia_cache_image` are compatible with null_safety.

Hope that helps
