### ISSUE TITLE
Flutter Web Image Stream issue

### ISSUE THREAD

**Issue by trueshail** [PauloniaAQP/paulonia_cache_image#6]
![Screen Shot 2021-02-02 at 2 00 48 PM](https://user-images.githubusercontent.com/45474067/106649102-1f846180-655f-11eb-8639-2f3407a8a605.png)
`Bad state: Stream has been disposed.
An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.`

This is the error I am getting on a flutter web project.
Can you please try to help on this?

**Comment by ChrisChV** [comment]
Hi @luv4ever2shail,
Can you pass me your `flutter doctor` report? And tell me if you added a special configuration when starting the package and if you used an image from the network or from cloud storage.

**Comment by trueshail** [comment]
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on macOS 11.1 20C69 darwin-x64, locale en-CA)
    • Flutter version 1.25.0-8.2.pre at /Users/shailkumar.patel/Documents/flutter
    • Framework revision b0a2299859 (4 weeks ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/shailkumar.patel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!

![image](https://user-images.githubusercontent.com/45474067/106694036-bbd15700-65a5-11eb-8957-a6add9aa4c85.png)

**Comment by ChrisChV** [comment]
Please detail under what circumstances the error occurs, so that I can reproduce it

**Comment by trueshail** [comment]
It occurs if there widget does builds multiple times in very short period. It throw that error.
For example : if m caching on the page2.  If I go to page2 from page1. The first time it works fine. But right after getting into the page2 if come back to page1 and go back in. It creates that error.
Sorry not the best explanation. Hope it helps.
Thank you

**Comment by ChrisChV** [comment]
Another question, what widget are you using to fetch the `PCacheImage()` provider? Are you using the `Image()` widget or something else in particular?

**Comment by trueshail** [comment]
Image widget
