### ISSUE TITLE
dependencies fail

### ISSUE THREAD

**Issue by javierbm7** [PauloniaAQP/paulonia_cache_image#7]
Hi when to try dependencies fail

Because every version of paulonia_cache_image depends on http ^0.12.2 and oci_balance_app depends on http ^0.13.0, paulonia_cache_image is forbidden.
So, because oci_balance_app depends on paulonia_cache_image ^0.2.2, version solving failed.
pub get failed (1; So, because oci_balance_app depends on paulonia_cache_image ^0.2.2, version solving failed.)

**Comment by ChrisChV** [comment]
Hí @javierbm7
Yes, the dependencies for this package have not yet been updated. We are thinking of updating the package with this, but we also want to add null-safety support. 
Another option is that you do a fork of this repo and you can update this dependency and use the package from your repo like this: https://dart.dev/tools/pub/dependencies#git-packages

**Comment by ChrisChV** [comment]
Fixed in version 0.3.0
